spring:
  application:
    name: eureka-server
server:
  port: 8081
  ip: 127.0.0.1
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: http://${server.ip}:${server.port}